### ISSUE TITLE
Investigar acerca de Angular

### ISSUE THREAD

**Issue by AleChirinos** [Los-senior-leads/Los-senior-leads#29]
Investigar más acerca del framework, saber como se hacen cosas especificas para el desarrollo del proyecto.
Investigar como hacer la función de usuarios  con distintos permisos.

**Comment by AleChirinos** [comment]
Login en Angular para distintos tipos de usuarios, con distintos permisos.

https://www.youtube.com/watch?v=6NKA6DWivWs

**Comment by AndreM22** [comment]
Documentación oficial de angular:
https://angular.io/docs
