### ISSUE TITLE
Diseñar las tablas para la base de datos

### ISSUE THREAD

**Issue by AndreM22** [Los-senior-leads/Los-senior-leads#30]
Diseñar las tablas para cada módulo especificando las llaves primarios y las relaciones

**Comment by AleChirinos** [comment]
Me parece importante que el tipo de datos para las columnas sea VARCHAR, ya que eso no esta especificado en los requerimientos y así pueda aceptar cualquier tipo de datos.

**Comment by AndreM22** [comment]
La tabla de "Empresas" es vital para la interrelación adecuada de todos los datos.

**Comment by AndreM22** [comment]
Para el diseño de la base de datos se usó la siguiente herramienta:
https://dbdiagram.io/home
