### ISSUE TITLE
Crear nuevo proyecto en Angular 

### ISSUE THREAD

**Issue by AleChirinos** [Los-senior-leads/Los-senior-leads#31]
Crear la base del proyecto en Angular y subirlo a la rama main para comenzar a trabajar

**Comment by AleChirinos** [comment]
Para el proyecto usaremos GitFlow, tenremos diferentes ramas y para juntarlas realizaremos pull requests entre las mismas hasta que lleguen a la rama develop

**Comment by AndreM22** [comment]
Referencia explicando como se implementa Gitflow:
https://www.atlassian.com/es/git/tutorials/comparing-workflows/gitflow-workflow
