### ISSUE TITLE
Investigar sobre Django y flask para el backend

### ISSUE THREAD

**Issue by darkv314** [Los-senior-leads/Los-senior-leads#36]
Se necesita un lenguaje de backend para la aplicaci[on que vamos a desarrollar, por lo que es necesario investigar sobre las tecnologías que podemos usar.

**Comment by AleChirinos** [comment]
Gracias a la investigación realizada, hicimos el cambio de la arquitectura de backend. Ahora se usará Flask.

**Comment by AndreM22** [comment]
Documentación de Flask:
https://flask.palletsprojects.com/en/2.0.x/
