### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by AleChirinos** [Los-senior-leads/Los-senior-leads#37]
El diseño del navbar debe ser general, debe mostrarse en todas las pantallas, excepto en la de login

**Comment by AleChirinos** [comment]
Mejorar el diseño de los botones para el uso del navbar.

**Comment by AndreM22** [comment]
Documentación de Flask:
https://flask.palletsprojects.com/en/2.0.x/

**Comment by AndreM22** [comment]
El navbar es de suma importancia para la navegación entre módulos y dependencias.
