### ISSUE TITLE
Investigar integración de flask y bases de datos sql

### ISSUE THREAD

**Issue by AndreM22** [Los-senior-leads/Los-senior-leads#39]
Profundizar conocimientos en base a lo que es flask y como integrarlo con sql

**Comment by AleChirinos** [comment]
La integracion de la base de datos MySQL y Flask, se vera implementada mediante una llamada desde el backend.

**Comment by AndreM22** [comment]
Video ejemplo de integración:
https://www.youtube.com/watch?v=IgCfZkR8wME&list=LL&index=2&t=3019s
