### ISSUE TITLE
Complementar casos de uso - Login super usuario

### ISSUE THREAD

**Issue by AleChirinos** [Los-senior-leads/Los-senior-leads#61]
Para esta parte del parcial es necesario el ingreso de los usuarios funcional con la base de datos, es por eso que debe crearse el login también para los súper usuarios. Se necesita un flujo para que el súper usuario pueda crear más usuarios y con esos mismos usuarios se pueda lograr un increso

**Comment by AndreM22** [comment]
La creación de un super usuario nos permite cumplir con los requisitos de manera efectiva.
