### ISSUE TITLE
Unir backend con front end - Escala Salarial

### ISSUE THREAD

**Issue by darkv314** [Los-senior-leads/Los-senior-leads#63]
Unir el backend de la aplicación con el frontend de la página de escala salarial. En la página debemos poder crear, modificar y ver los diferentes edificios desde el cliente.
Usar HTTP requests.

**Comment by AndreM22** [comment]
Para poder cumplir con lo diseñado en los mock ups, y los requerimientos tenemos que implementar una escala salarial con información de los edificios.
