### ISSUE TITLE
Backend - Reportes

### ISSUE THREAD

**Issue by darkv314** [Los-senior-leads/Los-senior-leads#65]
Agregar una página de reportes a las funcionalidades del backend. Esta página debe ser capaz de generar reportes para las diferentes páginas de la aplicación, mostrando información relevante para el usuario.

**Comment by AndreM22** [comment]
La información se representará mediante diversos gráficos que utilizaran los datos de la base de datos específica para desplegarse.

**Comment by AndreM22** [comment]
Los módulos que contarán con una opción de generación de reportes son: Empresas, Edificios y Escala Salarial
