### ISSUE TITLE
Base de datos - Usuarios

### ISSUE THREAD

**Issue by AleChirinos** [Los-senior-leads/Los-senior-leads#67]
Crear la base de datos para poder tener registrados a todos los usuarios, administradores y super usuarios en una base de datos. Cada usuario, administrador y super usuario debe tener su nombre de usuario, contraseña y su respectivo permiso.

**Comment by AndreM22** [comment]
Esta base de datos, al contrario de las otras, sirve más para tener permisos para las diferentes acciones en vez de participar en ellas.
