### ISSUE TITLE
Unir backend y frontend login

### ISSUE THREAD

**Issue by AleChirinos** [Los-senior-leads/Los-senior-leads#69]
Se debe unir el backend y el frontend para que un usuario pueda registrarse y lograr ingresar al sistema con el mismo usuario y contraseña. Aparte, debe poder mantener una base de datos actualizada, un frontend funcional y todos los métodos necesarios para el CRUD funcionales tanto para el backend, como para el frontend.

**Comment by AndreM22** [comment]
La unión de tanto back-end como front-end es muy importante para la verficación de permisos y el uso correcto de estos.
